### ISSUE TITLE
[🧹 CHORE]: `v2023.1` tracking ticket

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#1409]
### `v2023.1` Tracking tasks:

- [x] Check ALL OLD links in the docs pointing to the prev documentation version: https://roadrunner.dev/docs/plugins-logger/2.x/en in the CODE (SDK)
- [x] PGO profiles for the gRPC/HTTP/Jobs stress tests
- [x] Docs, Can't use dots in the configuration options: https://github.com/roadrunner-server/roadrunner/issues/1529
- [x] Update the video tutorials from this section: https://roadrunner.dev/docs/app-server-build/2.x/en (endure `v1` -> `v2`)
- [x] X-Sendfile tutorial update
- [ ] ~~Include Jobs/http/gRPC/etc stress testing in the CI~~
- [x] Docs: Reload plugin was removed
- [x] Update `composer.json` in the RR repository.
- [x] RPC Docs: https://github.com/roadrunner-server/roadrunner/issues/1045
- [x] SASL Kafka move to the brokers + kafka driver + `group_options` -> `consumer_group_options`
- [x] Docs + tests for the jobs statuses: https://github.com/roadrunner-server/status/pull/42
- [x] Docs: middleware order and caveats: https://github.com/roadrunner-server/roadrunner/issues/1501
- [x] Jobs docs: split into separate drivers instead of infinity single page.
- [x] AMQP requires queue and routing key (docs)
- [x] Docs: OpenTelemetry: https://github.com/spiral/roadrunner-docs/pull/127 + Docs about OTEL inside the JOBS plugin
- [x] Add info, that starting from the `v2023`, all RAW payloads would have the pipeline name set.
- [x] docs about `protobuf.so/dll/dylib` 
- [x] https://github.com/roadrunner-server/roadrunner/issues/1462, Added new `queue` info to the RR's payload sent to the underlying PHP process @butschster + tests  
- [x] Explain new metrics: https://github.com/roadrunner-server/jobs/pull/61 + add them to the RR Graphana dashboard
- [x] NGINX+RR docker container sample.
- [x] Docs: RR workers scaling, CPU/IO intensive tasks <-> worker.
- [x] BC - use `tar.gz` for the alpine releases: https://github.com/roadrunner-server/roadrunner/blob/master/.github/workflows/release.yml#L43. Also, since there were changes in the recent musl releases, check the possibility of using a regular Linux (non cgo) build.
- [x] https://github.com/roadrunner-server/roadrunner/issues/1424
- [x] Update supported metrics by the gRPC plugin (https://github.com/roadrunner-server/grpc/pull/77)
- [x] Configuration `v3` with `otel` as top level key: https://github.com/roadrunner-server/config/releases/tag/v4.2.0
- [x] `consume_id` docs (main rr repository, rr docs amqp section)
- [x] Jobs CLI commands are missing from the docs
- [x] RR docs, Locks: https://github.com/spiral/roadrunner-docs/issues/128
- [x] update `velox.toml` to include plugins v4 and check velox builds

**Comment by rustatian** [comment]
Links mapping:
| Old link |  New Link |
|-|-|
|`docs/app-server-https/2.x/en` | `docs/plugins-http/2023.x/en` |
| `docs/app-server-grpc/2.x/en` | `docs/plugins-grpc/2023.x/en` |
|`docs/middleware-otel/2.x/en`|`docs/plugins-otel/2023.x/en`|
|`docs/readme/2023.x/en`|`deleted`|
|`docs/plugins-jobs/2.x/en`|`split into separate links`|
|`amqp`|`docs/plugins-jobs-amqp/2023.x/en`|
|`beanstalk`|`docs/plugins-jobs-beanstalk/2023.x/en`|
|`kafka`|`docs/plugins-jobs-kafka/2023.x/en`|
|`local(boltdb)`|`docs/plugins-jobs-local(boltdb)/2023.x/en`|
|`memory`|`docs/plugins-jobs-memory/2023.x/en`|
|`nats`|`docs/plugins-jobs-nats/2023.x/en`|
|`sqs`|`docs/plugins-jobs-sqs/2023.x/en`|
|``|``|

**Comment by Kreczat** [comment]
Hi! What about release at the March end? Today is April, 3...

**Comment by rustatian** [comment]
> Hi! What about release at the March end? Today is April, 3...

Hey @Kreczat 👋🏻 

The release is planned for April 13 (next week), when all documentation issues will be resolved. If you want to try and give us your feedback, feel free to use the `v2023.1.0-rc.1` release. Thanks 👍🏻
