### ISSUE TITLE
[🧹 CHORE]: `v2023.2.0` tracking issue

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#1603]
### No duplicates 🥲.

- [x] **BETA RELEASE PLANNED DATE: 22 of JUNE: https://github.com/roadrunner-server/roadrunner/pkgs/container/roadrunner**
- [x] **PLANNED RELEASE DATE: 6th of JULY**

### What should be improved or cleaned up?

- [x] Jobs `timeout` option is missed (merge conflict?), add to the config/schema and docs.
- [x] Mention in the services docs about signals which RR sends to the underlying PHP process
- [x] Service plugin: new RPC options: https://github.com/roadrunner-server/service/pull/45
- [x] Redis plugin: updated to `v9` (now official go-redis client). Removed `IdleCheckFrequency` option (not needed). **Update docs!!!**
- [x] Make sure docs is up to date: https://github.com/roadrunner-server/jobs/pull/81
- [x] Tests: JOBS: metrics, JOBS API v2 tests
- [x] Update PHP subpackages to the most recent versions
- [x] TLS AMQP update docs: https://github.com/roadrunner-server/roadrunner/issues/1538
- [x] `after_init` add docs: https://github.com/roadrunner-server/server/pull/44
- [x] `kafka` SCRAM-SASL docs
- [x] Updated CORS handlers: https://github.com/roadrunner-server/roadrunner-docs/pull/140, https://github.com/roadrunner-server/headers/pull/48
