### ISSUE TITLE
`v2023.3.0` Tracking ticket [TODO]

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#1641]
## **Planned release date: October 6**

- [x] Status proto `v1beta` `->` `v1`. Backward compatible with the `v1beta`.
- [x] Docs note about dropping `Jaeger` dedicated hanlder (not `Jaeger` support): https://github.com/roadrunner-server/roadrunner/issues/1699, https://www.jaegertracing.io/docs/1.49/architecture/
- [x] OTEL kv docs: https://github.com/roadrunner-server/kv/pull/50
- [x] https://github.com/roadrunner-server/otel/pull/59
- [x] OTEL in-memory updated mechanism for removing items + updated configuration: https://github.com/roadrunner-server/memory/pull/77
- [x] Merge docs: https://github.com/roadrunner-server/roadrunner-docs/pull/146
- [x] Buf plugin new home: https://github.com/roadrunner-server/roadrunner/issues/1643, https://buf.build/community/roadrunner-server-php-grpc
- [x] Add note about the Baldinof Symfony integration from the discussion: https://discord.com/channels/538114875570913290/1128686379044454430/1128765328634150912
- [x] `sd_notify` new docs section (systemd related): https://github.com/roadrunner-server/roadrunner/issues/1654
- [x] `service` plugin new options: [FR](https://github.com/roadrunner-server/roadrunner/issues/1570)
- [x] `v2023.3` branch for the `roadrunner-docs`: [PR](https://github.com/roadrunner-server/roadrunner-docs/pull/143)
- [x] Documentation for the raw command: https://github.com/roadrunner-server/server/pull/51, https://github.com/roadrunner-server/roadrunner/issues/1667
- [x] Redis tracing/metrics: https://github.com/roadrunner-server/roadrunner/issues/1635 documentation.
- [x] Docs: Velox build section, how to build the server by cloning it.
- [x] `parallelism` option: https://github.com/roadrunner-server/jobs/pull/99
- [x] `kafka pings`: https://github.com/roadrunner-server/kafka/pull/199
- [x] Stream timeout option for the pool: https://github.com/roadrunner-server/sdk/pull/92
- [x] Uptrace sample: https://github.com/uptrace/uptrace/blob/master/example/docker/otel-collector.yaml
- [x] Dynamic workers scaling: https://github.com/roadrunner-server/roadrunner/issues/1728
