### ISSUE TITLE
`v2024.1.0` Tracking ticket [TODO]

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#1763]
```[tasklist]
### Tasks
- [x] Inline configuration: https://github.com/roadrunner-server/roadrunner/issues/935
- [x] HTTP <-> Worker protobuf transport: https://github.com/roadrunner-server/roadrunner/issues/1698
- [x] TLS plugin, activate for the v5 of plugins (version 2024.1)
- [x] Do we need to explicitly say about that in docs: https://github.com/orgs/roadrunner-server/discussions/1790#discussioncomment-7683420 ?
- [x] TLS Kafka docs and samples
- [x] Docs: https://github.com/roadrunner-server/sdk/pull/113
- [x] Search across the docs/readme (velox) and update RR 2023->2024
- [x] docs: `server.relay_timeout` was removed
- [x] docs: update tutorial 2023->2024
```
